name: Harper Media
favicon: null
layout_spectrum: 0.8197443995159119
typography_spectrum: 0.7893421892076731
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.75
  lightness: 0.9481438661459833
  saturation: 0.14891506917774677
  rhythmicContrast: 0.11757051246240735
purpose: []
